# Generated by Django 4.2.3 on 2023-08-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=' ', verbose_name='اسلاگ'),
        ),
    ]
