# Generated by Django 4.2.3 on 2023-08-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productcategory',
            new_name='category',
        ),
    ]
