# Generated by Django 4.2.3 on 2023-08-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='اسلاگ'),
        ),
    ]
