# Generated by Django 4.2.3 on 2023-08-09 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_alter_product_is_active_alter_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descrtiption',
            new_name='description',
        ),
    ]
