# Generated by Django 4.2.3 on 2023-08-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_rename_descrtiption_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='product_image', verbose_name='عکس محصول'),
        ),
    ]
