# Generated by Django 4.2.3 on 2023-08-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_module', '0003_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر'},
        ),
    ]
