# Generated by Django 4.2.3 on 2023-08-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=250, verbose_name='عنوان سایت')),
                ('site_url', models.CharField(max_length=250, verbose_name='دامنه سایت')),
                ('about_us', models.TextField(verbose_name='متن درباره ما')),
                ('contact_us_text', models.CharField(max_length=250, verbose_name='متن تماس با ما')),
                ('address', models.CharField(max_length=250, null=True, verbose_name='آدرس ما')),
                ('phone', models.CharField(max_length=250, null=True, verbose_name='تلفن تماس')),
                ('email', models.CharField(max_length=250, null=True, verbose_name='ایمیل')),
                ('info', models.TextField(null=True, verbose_name='درباره شرکت')),
                ('copy_right', models.CharField(max_length=255, verbose_name='متن کپی رایت')),
                ('is_main_setting', models.BooleanField(verbose_name='تنظیمات اصلی')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
