# Generated by Django 4.2.3 on 2023-08-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ دریافت'),
        ),
    ]
