# Generated by Django 4.2.3 on 2023-08-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_module', '0002_alter_contactus_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ دریافت'),
        ),
    ]
