# Generated by Django 4.2.3 on 2023-08-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_module', '0003_alter_contactus_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='profile_images', verbose_name='عکس پروفایل')),
            ],
        ),
    ]
