# Generated by Django 4.2.3 on 2023-08-12 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_module', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
