# Generated by Django 4.2.3 on 2023-08-13 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='url_title',
            field=models.CharField(max_length=250, unique=True, verbose_name='عنوان در url'),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان مقاله')),
                ('image', models.ImageField(null=True, upload_to='blog', verbose_name='عکس')),
                ('short_description', models.CharField(max_length=250, verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(verbose_name='متن')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('view', models.IntegerField(verbose_name='تعداد بازدید')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, verbose_name='اسلاگ')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_module.blogcategory', verbose_name='دسته بندی')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uesrs', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
