# Generated by Django 4.2.3 on 2023-08-13 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0002_alter_blogcategory_url_title_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user',
            new_name='auther',
        ),
    ]
