# Generated by Django 4.2.3 on 2023-08-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0003_rename_user_blog_auther'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='view',
            field=models.IntegerField(blank=True, verbose_name='تعداد بازدید'),
        ),
    ]
