# Generated by Django 4.2.3 on 2023-08-13 14:48

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0006_alter_blog_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
