# Generated by Django 4.2.3 on 2023-08-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0009_alter_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='view',
            field=models.IntegerField(blank=True, default=1, verbose_name='تعداد بازدید'),
        ),
    ]
