# Generated by Django 4.2.3 on 2023-08-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0012_alter_blogcomment_options_alter_blogcomment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='پاسخ ادمین'),
        ),
    ]
