# Generated by Django 4.2.3 on 2023-08-20 05:39

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0014_remove_blogcomment_parent_blogcomment_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[283, 202], upload_to='blog', verbose_name='عکس'),
        ),
    ]
