# Generated by Django 4.2.3 on 2023-08-22 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0017_alter_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='view',
        ),
    ]
