# Generated by Django 4.2.3 on 2023-08-22 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_module', '0018_remove_blog_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='آی پی کاربر')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='blog_module.blog', verbose_name='پست')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر مشاهده کرده')),
            ],
            options={
                'verbose_name': 'بازدید پست',
                'verbose_name_plural': 'بازدید های پست',
            },
        ),
    ]
