# Generated by Django 4.2.3 on 2023-08-22 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0019_blogvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='visit',
            field=models.IntegerField(blank=True, default=0, verbose_name='تعداد بازدید'),
        ),
        migrations.AlterField(
            model_name='blogvisit',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_visit', to='blog_module.blog', verbose_name='پست'),
        ),
    ]
