# Generated by Django 4.2.3 on 2023-08-20 05:54

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(crop=['center', 'center'], default=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[80, 80], upload_to='user_profile'),
            preserve_default=False,
        ),
    ]
