# Generated by Django 4.2.3 on 2023-08-20 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_alter_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
