# Generated by Django 4.2.3 on 2023-08-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0007_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='ثبت نشده', max_length=250, verbose_name='آدرس'),
        ),
    ]
