# Generated by Django 4.2.3 on 2023-09-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0008_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='order_count',
            field=models.IntegerField(default=0, null=True, verbose_name='تعداد خرید'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_buy',
            field=models.IntegerField(default=0, null=True, verbose_name='مجموع خرید'),
        ),
    ]
